# Generated by Django 3.1.7 on 2021-03-16 08:09

import backend.chat.models.chat_group_model
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Message creation time.', verbose_name='Timestamp')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('notification_status', enumfields.fields.EnumIntegerField(default=0, enum=backend.chat.models.chat_group_model.NotificationStatus, help_text='Message notifications. Disable if MUTE status, Enable if UNMUTE status.', verbose_name='Notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.image', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Chat Group',
                'verbose_name_plural': 'Chat groups',
                'ordering': ('id',),
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
