# Generated by Django 2.2 on 2021-03-20 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_message_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='notification_status',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
