# Generated by Django 2.2 on 2021-03-21 00:46

import backend.chat.models.chat_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0001_initial'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20210320_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Icon')),
                ('participants', models.ManyToManyField(related_name='chat_groups', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Chat Group',
                'verbose_name_plural': 'Chat groups',
                'ordering': ('id',),
            },
            managers=[
                ('objects', backend.chat.models.chat_model.ChatGroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Chat', verbose_name='Chat room'),
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
    ]
