# Generated by Django 2.2 on 2021-03-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210321_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='icon',
        ),
    ]
