# Generated by Django 3.1.7 on 2021-03-21 04:35

import backend.chat.models.chat_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210321_0051'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chat',
            managers=[
                ('objects', backend.chat.models.chat_model.ChatManager()),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_room',
            new_name='chat',
        ),
    ]
