# Generated by Django 3.1.7 on 2021-03-22 05:56

import backend.account.models.account_connection_history_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210321_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConnectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text="Unique ID of the user's device.", max_length=100, verbose_name='Device ID')),
                ('connection_status', enumfields.fields.EnumIntegerField(default=0, enum=backend.account.models.account_connection_history_model.ConnectionStatus, help_text='Account connection status.', verbose_name='Connection status')),
                ('last_connection', models.DateTimeField(auto_now=True, verbose_name='Last connection')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'unique_together': {('account', 'device_id')},
            },
        ),
    ]
