# Generated by Django 3.1.7 on 2021-03-16 08:09

import backend.filer.services
from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID of a file, universally Unique ID. An unique identifier generated for each file.', verbose_name='UUID')),
                ('filename', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Filename')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The server date and time when the file was finally processed and added to the system.', verbose_name='Created at')),
                ('creator', models.CharField(blank=True, help_text='The file creator.', max_length=100, null=True, verbose_name='Creator')),
                ('mime_type', models.CharField(blank=True, editable=False, help_text='The document version\'s file mimetype. MIME types are a standard way to describe the format of a file, in this case the file format of the document. Some examples: "text/plain" or "image/jpeg". ', max_length=255, null=True, verbose_name='MIME type')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to=backend.filer.services.upload_to, verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Image height')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Image Width')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('id',),
            },
        ),
    ]
