# Generated by Django 3.1.7 on 2021-03-17 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='Article cover')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Article cover',
                'verbose_name_plural': 'Article covers',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
