# Generated by Django 2.2.8 on 2021-03-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecomment_articlecommentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
    ]
