# Generated by Django 3.1.7 on 2021-03-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210317_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecover',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='Article cover'),
        ),
    ]
